### PR TITLE
Updates to fix deprecated Guzzle/PSR7 calls and general fixes

### PR DESCRIPTION
**Pull request by filipegar**
As briefly discussed on Rhosys' Discord community, this pull fixes a few different problems with the PHP SDK.

The strategy was:

1. Update Guzzle dep. to 'safe' versions (based on the package security advisories) and changed min. PHP version to comply with the other deps (lcobucci/jwt needs PHP >=8.1); added openssl as extension requirement for the package.
2. Because of the new minimum PHP version, applied typecasts and simplified a lot of the code (using ??, use statements, max, etc); mostly automated via PHPStorm fixes.
3. Fixed all GuzzleHttp and PSR7 package deprecations.
4. After fixed the undefined variable calls
5. Renewed php-cs-fixer config file, making it work again.
6. Fixed the constructor of all API classes to make the AuthressClient mandatory as it could not be instantiated with the past code due to missing baseUrl variable. (A better fix could be add these API calls as part of the actual AuthressClient and return these classes from within it.)

Despite the style changes (that pretty much changed all files), the major changes were made to the deprecated stuff itself and a few bug fixes.

### CODE REVIEW

**Comment by wparad** [comment]
First of all **Thank you**, for taking the time to clean up these files that certainly had a bunch of legacy crud. The team really appreciates it!

Second of all some **Background**: There is definitely still some "bad code" where we are doing things that likely need not to be done, in a later version `0.4`/`1.0`, we'll likely also remove that code. Thank you for freeing us of some of it. The version of the library you were looking at was made by a code generator, so we avoided touch parts that did not need to be changed. Now that we are taking ownership of those parts too, our team will need to go back through and take a detailed review of all the different classes, models, and apis. This is just a heads up. In most of these cases we might remove some of the unnecessary utility class methods like `$offsetExists`, it isn't clear for us that things like that offer value.

Lastly, given the size of this PR, I don't think there is any good way to test this. So here's what we are going to do:

* **Release** We are going to release a new version `0.3` with these changes instead. That will get the changes out so that you can start using them. This way we also prevent any bugs that we might have introduced from affecting others using this SDK.

* **Future bugs** I'm going to let any bugs or issues with this code go through for now, since you are testing with it, and the new version won't be used by anyone yet, you'll be able to find these the quickest and make the appropriate fixes for them.

* **Creating PRs** Going forward, we aren't going to accept any PR that has both style changes AND functional changes in the same PR, even if these are separated into different commits. That means if we want to rename something across files and make a bug fix these need to be two separate PRs. In the exceptional case that there is only a single file change, separate commits (one style change, and then one functional change) is totally okay!

**Comment by wparad** [comment]
There's a new version `0.3.56`, I'm sure this won't be the last find as we find additional things we want to change, but that should enable you to take your next steps.

**Comment by filipegar** [comment]
Thanks for merging, @wparad - and happy New Year!

Indeed, I saw a lot of duplicate code that look generated. For sure something we can optimize for the future.
I do agree with your comments for next merges - I'm really sorry for messing with your code history log; when I saw PHPStorm ran the styling, I would have lost a lot of the changes not commited. 

I should start further testing on the coming weeks but looks like it is good enough for now. Hope I can help you expand and improve it. :)

**Comment by wparad** [comment]
> Thanks for merging, @wparad - and happy New Year!
> 
> Indeed, I saw a lot of duplicate code that look generated. For sure something we can optimize for the future. I do agree with your comments for next merges - I'm really sorry for messing with your code history log; when I saw PHPStorm ran the styling, I would have lost a lot of the changes not commited.
> 
> I should start further testing on the coming weeks but looks like it is good enough for now. Hope I can help you expand and improve it. :)

@filipegar no worries, everything is good here. We look forward to whatever suggested improvements you have! GL.

**Pull request merged**
